etcd:
  hostname: etcd
  image: coreos/etcd
  ports: [ "4001:4001", "7001:7001" ]
  command: -addr=etcd:4001
#zookeeper:
#  image: jplock/zookeeper:3.4.5
#  ports: [ "2181:2181" ]
mesos:
  hostname: mesos
  image: mesosphere/mesos:0.22.0-1.0.ubuntu1404
  entrypoint: mesos-local
  ports: [ "5050:5050" ]
  environment:
  - MESOS_HOSTNAME=mesos
  - MESOS_PORT=5050
  - MESOS_LOG_DIR=/var/log/mesos
  - MESOS_QUORUM=1
  - MESOS_REGISTRY=in_memory
  - MESOS_WORK_DIR=/var/lib/mesos
#  - MESOS_ZK=zk://zookeeper:2181/mesos
  links:
  - etcd
#  - zookeeper
apiserver:
  hostname: apiserver
  image: mesosphere/kubernetes-mesos:latest
  entrypoint:
  - /bin/bash
  - "-c"
  - >
    echo "Hostname: $(hostname -f) ($(hostname -f | xargs getent hosts | cut -d' ' -f1 | sort -u | tail -1))" &&
    echo "mesos-master = mesos:5050" >> /opt/mesos-cloud.conf &&
    timeout 10 bash -c "while ! echo exit | nc -z $(getent hosts etcd | cut -d' ' -f1 | sort -u | tail -1) 4001; do sleep 0.5; done" &&
    timeout 10 bash -c "while ! echo exit | nc -z $(getent hosts mesos | cut -d' ' -f1 | sort -u | tail -1) 5050; do sleep 0.5; done" &&
    /kubernetes-mesos/bin/km apiserver
    --address=$(xargs getent hosts apiserver | cut -d' ' -f1 | sort -u | tail -1)
    --external_hostname=apiserver
    --etcd_servers=http://etcd:4001
    --portal_net=10.10.10.0/24
    --port=8888
    --cloud_provider=mesos
    --cloud_config=/opt/mesos-cloud.conf
    --v=2
  ports: [ "8888:8888" ]
  links:
  - etcd
  - mesos
controller:
  hostname: controller
  image: mesosphere/kubernetes-mesos:latest
  entrypoint:
  - /bin/bash
  - "-c"
  - >
    echo "Hostname: $(hostname -f) ($(hostname -f | xargs getent hosts | cut -d' ' -f1 | sort -u | tail -1))" &&
    echo "mesos-master = mesos:5050" >> /opt/mesos-cloud.conf &&
    timeout 20 bash -c "while ! echo exit | nc -z $(getent hosts mesos | cut -d' ' -f1 | sort -u | tail -1) 5050; do sleep 0.5; done" &&
    timeout 10 bash -c "while ! echo exit | nc -z $(getent hosts apiserver | cut -d' ' -f1 | sort -u | tail -1) 8888; do sleep 0.5; done" &&
    /kubernetes-mesos/bin/km controller-manager
    --master=http://apiserver:8888
    --cloud_config=/opt/mesos-cloud.conf
    --v=2
  links:
  - mesos
  - apiserver
scheduler:
  hostname: scheduler
  image: mesosphere/kubernetes-mesos:latest
  entrypoint:
  - /bin/bash
  - "-c"
  - >
    echo "Hostname: $(hostname -f) ($(hostname -f | xargs getent hosts | cut -d' ' -f1 | sort -u | tail -1))" &&
    echo "mesos-master = mesos:5050" >> /opt/mesos-cloud.conf &&
    timeout 10 bash -c "while ! echo exit | nc -z $(getent hosts etcd | cut -d' ' -f1 | sort -u | tail -1) 4001; do sleep 0.5; done" &&
    timeout 10 bash -c "while ! echo exit | nc -z $(getent hosts mesos | cut -d' ' -f1 | sort -u | tail -1) 5050; do sleep 0.5; done" &&
    timeout 10 bash -c "while ! echo exit | nc -z $(getent hosts apiserver | cut -d' ' -f1 | sort -u | tail -1) 8888; do sleep 0.5; done" &&
    /kubernetes-mesos/bin/km scheduler
    --address=$(xargs getent hosts scheduler | cut -d' ' -f1 | sort -u | tail -1)
    --hostname_override=scheduler
    --etcd_servers=http://etcd:4001
    --mesos_user=root
    --api_servers=http://apiserver:8888
    --mesos_master=mesos:5050
    --v=2
  links:
  - etcd
  - mesos
  - apiserver
